version: "3.8" # Docker Engine release: 19.03.0+
services:
  jupyterlab-pyspark:
    image: jupyter/pyspark-notebook:latest
    container_name: jupyterlab-pyspark
    restart: always
    command: start-notebook.sh --NotebookApp.password=sha256:bb8c050b9545:c21d963d0765635c8494c787935802d4511e0411fb3d4a555f45e2ab0a776c80
    volumes:
#      - ./work:/home/jovyan/work
      - ./:/home/jovyan/work ' # Montar o diretório do projeto
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/home/jovyan/minio_datalake  # Adicionar o diretório do projeto ao PYTHONPATH
    ports:
      - 8888:8888
      - 4040:4040

  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio-data:/data
    ports:
      - 9000:9000
      - 9001:9001
    restart: always

volumes:
  minio-data:
